# Generated by Django 4.2.28 on 2026-02-24 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('technology', 'Technology'), ('sports', 'Sports'), ('politics', 'Politics'), ('fashion', 'Fashion'), ('music', 'Music'), ('gaming', 'Gaming'), ('food', 'Food & Lifestyle'), ('business', 'Business'), ('science', 'Science'), ('other', 'Other')], db_index=True, max_length=50)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('reddit', 'Reddit'), ('linkedin', 'LinkedIn'), ('threads', 'Threads')], max_length=50)),
                ('description', models.TextField()),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('velocity', models.CharField(choices=[('exploding', 'Exploding'), ('rising', 'Rising'), ('steady', 'Steady'), ('declining', 'Declining')], default='rising', max_length=20)),
                ('embed_url', models.URLField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['category', 'score'], name='trends_tren_categor_cec03e_idx'), models.Index(fields=['created_at', 'score'], name='trends_tren_created_9f9065_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='trends.trend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'trend')},
            },
        ),
    ]
