# Generated by Django 4.2.28 on 2026-02-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trend',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('google_trends', 'Google Trends'), ('news', 'News'), ('stocks', 'Stocks'), ('youtube', 'YouTube'), ('music', 'Music')], db_index=True, default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='trend',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
