# Generated by Django 4.2.28 on 2026-02-25 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trends', '0002_trend_external_url_trend_source_trend_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_comments', to='trends.trend')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
